xspring.application.name=gestao-tcc

spring.docker.compose.enabled=false

# Configurações de conexão para o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestao_tcc
spring.datasource.username=admin
spring.datasource.password=senha_secreta
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate / JPA e Flyway
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/sigtcc
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/sigtcc/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.audiences=sigtcc-backend
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

## H2 Database em memÃ³ria para dev local
#spring.datasource.url=jdbc:h2:mem:gestaotcc;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
