name: Lint de Markdown

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-lint:
    name: Verificar formatação do Markdown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: "**/*.md"