name: Checagem de Links

on:
  pull_request:
    branches:
      - main

jobs:
  link-checker:
    name: Verificar Links Quebrados
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Executar verificador de links
        uses: lycheeverse/lychee-action@v2
        with:
          args: './**/*.md'
