name: Verificação de Formatação (Prettier)

on:
  pull_request:
    branches:
      - main

jobs:
  formatacao:
    name: Checar Formatação de Código
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Executar Prettier
        run: npx prettier --check "." --ignore-path .gitignore
